// app/layout.tsx
import './globals.css'
// Perhatikan tanda @/components/ di bawah ini akan otomatis membaca ke root jika tsconfig Anda default
import { ThemeProvider } from '@/components/ThemeProvider'

export const metadata = {
  title: 'PXLabs Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gray-50 dark:bg-[#121212] transition-colors duration-300">
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}